version: '3.8'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chat_server
    environment:
      - PORT=${SERVER_PORT:-3000}
      - NODE_ENV=development
    ports:
      - "${SERVER_PORT:-3000}:3000"
    networks:
      - chatnet
    restart: unless-stopped
    command: npm run start:dev
    volumes:
      - ./server/.env:/app/.env
      - ./server/src:/app/src

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: chat_client
    environment:
      - PORT=${CLIENT_PORT:-5173}
    ports:
      - "${CLIENT_PORT:-5173}:5173"
    networks:
      - chatnet
    restart: unless-stopped


networks:
  chatnet:
    driver: bridge
